name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - junho

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # 1. working-directory 이름을 대문자 포함 실제 폴더명인 PickMeal로 수정
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./PickMeal

      # 2. 여기도 마찬가지로 PickMeal로 수정
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./PickMeal

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: pickmeal
          environment_name: Pickmeal-env
          version_label: ${{ github.sha }}
          region: ap-northeast-2
          # 3. 배달 패키지 경로도 PickMeal로 시작하도록 수정
          deployment_package: PickMeal/build/libs/pickmeal-0.0.1-SNAPS